### ISSUE TITLE
python and javascript prompts in subdirectories not found

### ISSUE THREAD

**Issue by JCourt1** [promptfoo/promptfoo#1060]
If you specify a python or javascript prompt in a subdirectory, like so:

```
prompts:
  - file://./prompts/prompt.py
```

Results in the following error, even though the file is indeed present at `./prompts/prompt.py`:

```
> npx promptfoo@latest eval --verbose
Reading prompts from ["file://./prompts/prompt.py"]
node:fs:603
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'prompt.py'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at processPythonFile (/home/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/prompts/processors/python.js:80:28)
    at processPrompt (/home/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/prompts/index.js:112:47)
    at readPrompts (/home/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/prompts/index.js:134:35)
    at resolveConfigs (/home/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/main.js:130:59)
    at runEvaluation (/home/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/main.js:546:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (/home/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/main.js:705:9) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'prompt.py'
}
```

Somewhere, it appears to be stripping the path of all directories and just retaining the filename, then trying to look for it in the current directory. If you move the prompt from `./prompts/prompt.py` to `./prompt.py`, it works. This is problematic though, because having to store all prompts in the current directory can get very messy.

I have tested that this is currently happening for python and javascript prompts - but not for yaml / json.

Version:
```
>  npx promptfoo@latest --version
0.68.0
```

**Comment by typpo** [comment]
Thanks for the report, we'll get this fixed.  A potential temp workaround may be to revert to version 0.66.0.
