### ISSUE TITLE
Output to google-sheets failed

### ISSUE THREAD

**Issue by kackyt** [promptfoo/promptfoo#1366]
**Describe the bug**
Writing to the sheet causes an error and cannot be executed.

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

1. OpenAI API Key and Google Cloud Credential write to .env
2. Edit 'examples/google-sheets/promptfooconfig.yaml' Writing output to a sheet
3. Run 'npx promptfoo@latest eval'

```
Error: Invariant failed: Unsupported output file format undefined. Please use one of: csv, html, json, txt, yaml, yml.
    at invariant (C:\Users\tkakizaki\AppData\Local\npm-cache\_npx\81bbc6515d992ace\node_modules\tiny-invariant\dist\tiny-invariant.cjs.js:14:11)
    at writeOutput (C:\Users\tkakizaki\AppData\Local\npm-cache\_npx\81bbc6515d992ace\node_modules\promptfoo\dist\src\util\index.js:93:34)
    at runEvaluation (C:\Users\tkakizaki\AppData\Local\npm-cache\_npx\81bbc6515d992ace\node_modules\promptfoo\dist\src\commands\eval.js:140:46)
    at async doEval (C:\Users\tkakizaki\AppData\Local\npm-cache\_npx\81bbc6515d992ace\node_modules\promptfoo\dist\src\commands\eval.js:240:5)
```

**Expected behavior**
Output result to google sheets.

**Screenshots**

![screeenshot02](https://github.com/user-attachments/assets/0e70f803-06db-4297-ae80-5fbd2b670169)

**System information (please complete the following information):**

- Windows 10
- nodejs 20.16.0
- Promptfoo version: 0.74.0

**Additional context**

**Comment by typpo** [comment]
Thanks for the report. #1367 should fix this.

**Comment by typpo** [comment]
This should be good in the latest release
