### ISSUE TITLE
[FAIL] Error: Unknown assertion type: similarity

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#146]
```
[FAIL] Error: Unknown assertion type: similarity

Error: Unknown assertion type: similarity
at runAssertion (/Users/user/.nvm/versions/node/v19.9.0/lib/node_modules/promptfoo/dist/src/assertions.js:458:11)
at runAssertions (/Users/user/.nvm/versions/node/v19.9.0/lib/node_modules/promptfoo/dist/src/assertions.js:48:30)
at async Evaluator.runEval (/Users/user/.nvm/versions/node/v19.9.0/lib/node_modules/promptfoo/dist/src/evaluator.js:168:37)
at async /Users/user/.nvm/versions/node/v19.9.0/lib/node_modules/promptfoo/dist/src/evaluator.js:404:25
```

I am getting this error when running `promptfoo eval` with the default `promptfooconfig.yaml` and `providers: [ollama:llama2:13b]`.

How can I fix this error?

**Comment by jamesbraza** [comment]
https://promptfoo.dev/docs/getting-started uses "similar", not "similarity".

https://github.com/promptfoo/promptfoo/blob/0.23.1/src/onboarding.ts#L53

I think that line ^^^ should be updated to "similar"

**Comment by typpo** [comment]
Thanks for the catch!  

(Side note - the similarity assertion type relies on OpenAI embeddings and will require an API key)
