### ISSUE TITLE
Promptfoo cannot decode special characters

### ISSUE THREAD

**Issue by balintdom** [promptfoo/promptfoo#1510]
**Describe the bug**
When the input message contains the hungarian `Á` or `Ő` characters I get the following error

```
Python code execution failed: Error running Python script: UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 25: character maps to <undefined>
Stack Trace: Error: UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 25: character maps to <undefined>
    at PythonShell.parseError (C:\Users\bdomonkos\AppData\Roaming\nvm\v20.9.0\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\bdomonkos\AppData\Roaming\nvm\v20.9.0\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\bdomonkos\AppData\Roaming\nvm\v20.9.0\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\bdomonkos\AppData\Roaming\nvm\v20.9.0\node_modules\promptfoo\dist\src\python\wrapper.py", line 33, in <module>
      data = json.load(fp)
             ^^^^^^^^^^^^^
    File "C:\Users\bdomonkos\miniconda3\envs\pythonservice\Lib\json\__init__.py", line 293, in load
      return loads(fp.read(),
                   ^^^^^^^^^
    File "C:\Users\bdomonkos\miniconda3\envs\pythonservice\Lib\encodings\cp1250.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**To Reproduce**
Run promptfoo with user prompts containing the hungarian `Á` or `Ő` characters.

**Expected behavior**
Promptfoo should handle special characters or provide the opportunity to change the encoding.

**System information (please complete the following information):**

- Promptfoo version: 0.80.2

**Comment by mldangelo** [comment]
Hi @balintdom, 

Thank you for reporting this issue. We’ve just issued a release in [v0.80.3](https://github.com/promptfoo/promptfoo/releases/tag/0.80.3) that addresses this issue by ensuring that UTF-8 encoding is used for Python IPC. This should resolve the UnicodeDecodeError you encountered. Please update to the latest version and let us know if you continue to experience any problems. Thanks again and please don't hesitate to reach out.
