### ISSUE TITLE
Unable to delete all evals

### ISSUE THREAD

**Issue by pbackx** [promptfoo/promptfoo#1578]
**Describe the bug**
When running `npx promptfoo delete eval all` a foreign key contraint error is thrown. Making it impossible to delete all evals in one go.

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

1. Run a few evals with `npx promptfoo eval`
2. Make sure evals are in the database with `npx promptfoo list evals`
3. Try to delete them all with `npx promptfoo delete eval all`
4. See the following error:

```
? Are you sure you want to delete all stored evaluations? This action cannot be undone. yes

C:\dev\promptfoo\node_modules\drizzle-orm\better-sqlite3\session.cjs:88
    return this.stmt.run(...params);
                     ^
SqliteError: FOREIGN KEY constraint failed
    at PreparedQuery.run (C:\dev\promptfoo\node_modules\drizzle-orm\better-sqlite3\session.cjs:88:22)
    at QueryPromise.run (C:\dev\promptfoo\node_modules\drizzle-orm\sqlite-core\query-builders\delete.cjs:97:28)
    at deleteAllEvals (C:\dev\promptfoo\node_modules\promptfoo\dist\src\util\index.js:812:37)
    at handleEvalDeleteAll (C:\dev\promptfoo\node_modules\promptfoo\dist\src\commands\delete.js:28:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (C:\dev\promptfoo\node_modules\promptfoo\dist\src\commands\delete.js:70:13) {
  code: 'SQLITE_CONSTRAINT_FOREIGNKEY'
}

Node.js v20.13.1
```

**Expected behavior**
From my understanding of the CLI docs, `delete eval all` should delete all evals.

**System information (please complete the following information):**

- Promptfoo version: 0.83.2

I am running this on Windows using Powershell

**Additional context**
I have already tried to completely remove the .promptfoo folder, but even running a single eval and trying to delete all causes the issue.

**Comment by typpo** [comment]
This is fixed in the latest release!  Thanks for flagging

**Comment by pbackx** [comment]
Tested and working. Thanks for the quick fix!
