### ISSUE TITLE
Allowing `providers` to be string in `promptfooconfig.yaml`

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#165]
Here is part of my `promptfooconfig.yaml`:

```yaml
---
prompts: [prompts.txt]
providers: [ollama:llama2:13b]
```

[`pre-commit`'s `check-yaml`](https://pre-commit.com/hooks.html) is flagging my `promptfooconfig.yaml`'s `providers` entry:

```
check yaml....................................................................Failed
- hook id: check-yaml
- exit code: 1

while scanning a plain scalar
  in "promptfooconfig.yaml", line 3, column 13
found unexpected ':'
  in "promptfooconfig.yaml", line 3, column 19
```

This can be fixed by making `providers` a string: `providers: "[ollama:llama2:13b]"`.

However, when I do that, now `promptfoo` fails:

```
>  promptfoo eval
node:internal/modules/cjs/loader:1090
  const err = new Error(message);
              ^

Error: Cannot find module '/Users/user/code/repo/[ollama:llama2:13b]'
Require stack:
- /Users/user/.nvm/versions/node/v19.9.0/lib/node_modules/promptfoo/dist/src/providers.js
- /Users/user/.nvm/versions/node/v19.9.0/lib/node_modules/promptfoo/dist/src/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at /Users/user/.nvm/versions/node/v19.9.0/lib/node_modules/promptfoo/dist/src/providers.js:200:132
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadApiProvider (/Users/user/.nvm/versions/node/v19.9.0/lib/node_modules/promptfoo/dist/src/providers.js:200:32)
    at async loadApiProviders (/Users/user/.nvm/versions/node/v19.9.0/lib/node_modules/promptfoo/dist/src/providers.js:45:17)
    at async Command.<anonymous> (/Users/user/.nvm/versions/node/v19.9.0/lib/node_modules/promptfoo/dist/src/main.js:257:33) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/user/.nvm/versions/node/v19.9.0/lib/node_modules/promptfoo/dist/src/providers.js',
    '/Users/user/.nvm/versions/node/v19.9.0/lib/node_modules/promptfoo/dist/src/main.js'
  ]
}

Node.js v19.9.0
```

It would be cool if `providers` in YAML could be a string

**Comment by typpo** [comment]
Does it work with an array of strings?

```yaml
providers: ["ollama:llama2:13b"]
```

**Comment by jamesbraza** [comment]
Oh nice thinking 🚀  yeah that does work! Thanks for thinking outside of the box
