### ISSUE TITLE
Vulnerability report for red teaming evaluation fails to show in the web app with: "Cannot read properties of undefined (reading 'type')"

### ISSUE THREAD

**Issue by alex-pollan** [promptfoo/promptfoo#1899]
**Describe the bug**
The vulnerability report for red teaming evaluation fails to show in the web app. When I click on the button to see the report, the page displays an error:

```
Unexpected Application Error!

Cannot read properties of undefined (reading 'type')

TypeError: Cannot read properties of undefined (reading 'type')
    at http://localhost:15500/assets/index-BPrn51S5.js:767:15637
    at Array.map (<anonymous>)
    at WZe (http://localhost:15500/assets/index-BPrn51S5.js:767:15605)
    at $P (http://localhost:15500/assets/index-BPrn51S5.js:38:17031)
    at zW (http://localhost:15500/assets/index-BPrn51S5.js:40:44104)
    at QW (http://localhost:15500/assets/index-BPrn51S5.js:40:39822)
    at Gae (http://localhost:15500/assets/index-BPrn51S5.js:40:39748)
    at J2 (http://localhost:15500/assets/index-BPrn51S5.js:40:39598)
    at V4 (http://localhost:15500/assets/index-BPrn51S5.js:40:35960)
    at UW (http://localhost:15500/assets/index-BPrn51S5.js:40:34907)
```

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

1. Run a red teaming evaluation `npx promptfoo redteam run`
2. Run 'npx promptfoo view'
3. In the web browser, in the promptfoo web app, select `Evals`
4. Select a red teaming evaluation in the dropdown
5. Click on 'Vulnerability Report'
7. See error

**Expected behavior**
The vulnerability report must be displayed.

**Screenshots**

![image](https://github.com/user-attachments/assets/fcaa5b42-6ed2-4d8b-b014-5535fc551e89)

**System information (please complete the following information):**

- Promptfoo version: 0.93.1

**Additional context**
N/A.

**Comment by typpo** [comment]
Hard to tell with the minified error, but I _think_ this was introduced in 0.93.0 with 04e45639a3e0f491e159b0ca7143473a273c3b90.  I'll get a fix in.  You may be able to temporarily work around by using version 0.92.3.

**Comment by alex-pollan** [comment]
@typpo This now works correctly with v0.93.3, good work!

Thanks!

**Comment by typpo** [comment]
Great!
