### ISSUE TITLE
Unable to open promptfoo link from `promptfoo share`

### ISSUE THREAD

**Issue by albertlieyingadrian** [promptfoo/promptfoo#1906]
```Uncaught (in promise) QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'ResultsViewStorage' exceeded the quota.
    at Object.setItem (921-ea4bddb5c25058ea.js:44:2429)
    at v (921-ea4bddb5c25058ea.js:44:4601)
    at 921-ea4bddb5c25058ea.js:44:4715
    at setTable (712-08d720048b34c52c.js:1:859)
    at e (712-08d720048b34c52c.js:1:42556)
```
<img width="685" alt="Screenshot 2024-10-16 at 8 48 38 PM" src="https://github.com/user-attachments/assets/7e0549a5-f953-48c9-b0dc-867755c76c27">

**Comment by albertlieyingadrian** [comment]
oh maybe related to this issue https://github.com/promptfoo/promptfoo/issues/1731#issue-2540416297

**Comment by mldangelo** [comment]
Closing this as a duplicate of #1731.

This issue was caused by the old `app.promptfoo.dev` sharing infrastructure which stored eval results in browser localStorage. Large evals would exceed the browser's ~5MB localStorage quota, causing the `QuotaExceededError` you experienced.

We've since completely rebuilt the sharing infrastructure with the new `promptfoo.app` backend. The data is now stored server-side, so there are no more localStorage quota limitations.

If you run into any issues with the new sharing system, please open a fresh issue and we'll take a look. Thanks for reporting this!

**Comment by kkahadze** [comment]
Linear issue: https://linear.app/promptfooo/issue/ENG-314/unable-to-open-promptfoo-link-from-promptfoo-share
