### ISSUE TITLE
promptfoo view not able to connect to server via browser on 0.25.0

### ISSUE THREAD

**Issue by NathanKarthik1996** [promptfoo/promptfoo#228]
Hello,

I am currently using VSCODE dev container to install promptfoo. When I do a promptfoo view on 0.25.0, I run into the following on the browser:

Application error: a client-side exception has occurred (see the browser console for more information).

This is what I see on the browser console:

596-297f7ff4a0436e87.js:1 TypeError: Cannot read properties of null (reading 'toFixed')
    at eo (891-0286b3010dc452ac.js:1:7166)
    at ed (891-0286b3010dc452ac.js:1:8541)
    at ri (fd9d1056-fba4b53a2f01213b.js:9:38931)
    at im (fd9d1056-fba4b53a2f01213b.js:9:111754)
    at oM (fd9d1056-fba4b53a2f01213b.js:9:90098)
    at fd9d1056-fba4b53a2f01213b.js:9:89920
    at oT (fd9d1056-fba4b53a2f01213b.js:9:89927)
    at ov (fd9d1056-fba4b53a2f01213b.js:9:87565)
    at oy (fd9d1056-fba4b53a2f01213b.js:9:86427)
    at E (596-297f7ff4a0436e87.js:25:1389)

**Comment by typpo** [comment]
Have you run any evals / are you able to share the config of that eval and/or the contents of `~/.promptfoo/output/latest.json`?

**Comment by typpo** [comment]
Release 0.25.1 contains a possible fix.
