### ISSUE TITLE
Getting Started -  TypeError: pathOrGlob.startsWith is not a function

### ISSUE THREAD

**Issue by gautam-goudar** [promptfoo/promptfoo#271]
I am getting started by following the documentation 
https://www.promptfoo.dev/docs/getting-started

When I run the command
```
npx promptfoo@latest eval
```

I see the below error
```
TypeError: pathOrGlob.startsWith is not a function
    at /Users/[redacted]/Documents/my-learning/promptfoo/node_modules/promptfoo/dist/src/prompts.js:107:28
    at Array.flatMap (<anonymous>)
    at readPrompts (/Users/[redacted]/Documents/my-learning/promptfoo/node_modules/promptfoo/dist/src/prompts.js:106:45)
    at Command.<anonymous> (/Users/[redacted]/Documents/my-learning/promptfoo/node_modules/promptfoo/dist/src/main.js:258:57)
    at Command.listener [as _actionHandler] (/Users/[redacted]/Documents/my-learning/promptfoo/node_modules/commander/lib/command.js:482:17)
    at /Users/[redacted]/Documents/my-learning/promptfoo/node_modules/commander/lib/command.js:1283:65
    at Command._chainOrCall (/Users/[redacted]/Documents/my-learning/promptfoo/node_modules/commander/lib/command.js:1177:12)
    at Command._parseCommand (/Users/[redacted]/Documents/my-learning/promptfoo/node_modules/commander/lib/command.js:1283:27)
    at /Users/[redacted]/Documents/my-learning/promptfoo/node_modules/commander/lib/command.js:1081:27
    at Command._chainOrCall (/Users/[redacted]/Documents/my-learning/promptfoo/node_modules/commander/lib/command.js:1177:12)
```

Version Details
---
node version : v18.15.0
npm version:  9.5.0

**Comment by typpo** [comment]
Hi @gautam-goudar, try quoting the prompts:

```yaml
prompts:
  - 'Convert this English to {{language}}: {{input}}'
  - 'Translate to {{language}}: {{input}}'
```

**Comment by gautam-goudar** [comment]
Thank you.  Quoting the prompts worked.

**Comment by typpo** [comment]
Thanks, documentation is now corrected
