### ISSUE TITLE
error: promptfoo eval --config folder/promptfooconfig.yaml

### ISSUE THREAD

**Issue by arm-diaz** [promptfoo/promptfoo#302]
Hey,

I am getting the following error when I run `eval` using --config with a directory.

Example:
npx promptfoo@latest eval --config examples/amazon-bedrock/promptfooconfig.yaml

```
promptfoo/dist/src/prompts.js:111
            if (pathOrGlob.startsWith('file://')) {
                           ^

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at promptfoo/dist/src/prompts.js:111:28
    at Array.flatMap (<anonymous>)
    at readPrompts (promptfoo/dist/src/prompts.js:110:45)
    at Command.<anonymous> promptfoo/dist/src/main.js:260:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

It runs fine when the `promptfooconfig.yaml` is on the root directory, e.g. `npx promptfoo@latest eval`

**Comment by typpo** [comment]
Thanks for catching this. Fix in #304
