### ISSUE TITLE
Still Getting `E2BIG` Error

### ISSUE THREAD

**Issue by sangwoo-joh** [promptfoo/promptfoo#646]
I thought #635 fixed this issue, but it didn't.
I'm still getting `E2BIG` errors in `promptfoo view` page.

```
FAILError: spawn E2BIG

Error: spawn E2BIG
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at spawn (node:child_process:757:9)
    at new PythonShell (prompt-pioneer/node_modules/python-shell/index.js:130:55)
    at prompt-pioneer/node_modules/python-shell/index.js:252:27
    at new Promise (<anonymous>)
    at PythonShell.run (prompt-pioneer/node_modules/python-shell/index.js:251:16)
    at runPython (prompt-pioneer/node_modules/promptfoo/dist/src/python/wrapper.js:28:58)
    at PythonProvider.callApi (prompt-pioneer/node_modules/promptfoo/dist/src/providers/pythonCompletion.js:40:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Evaluator.runEval (prompt-pioneer/node_modules/promptfoo/dist/src/evaluator.js:248:30)
```

**Comment by typpo** [comment]
Seems like the implementation will have to be updated to send data through stdin

https://github.com/extrabacon/python-shell/issues/179
https://github.com/extrabacon/python-shell#exchanging-data-between-node-and-python

**Comment by sangwoo-joh** [comment]
@typpo I have another workaround with a temporary json file, and if you don't mind can I make a PR for this?

**Comment by typpo** [comment]
Yes, that would work too!  Definitely open to a PR @sangwoo-joh

**Comment by sangwoo-joh** [comment]
@typpo Thanks, I made a #660 ! It would be appreciated if you review this.
