### ISSUE TITLE
Unable to share result, is the API server down?

### ISSUE THREAD

**Issue by chaofuyang** [promptfoo/promptfoo#678]
In my local laptop, 

`promptfoo eval` works but `promptfoo eval --share` yields the following error:

```
/Users/chaofuyang/.nvm/versions/node/v20.10.0/lib/node_modules/promptfoo/node_modules/node-fetch/lib/index.js:273
				return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
				                           ^
FetchError: invalid json response body at https://api.promptfoo.dev/api/eval reason: Unexpected token 'I', "Internal s"... is not valid JSON
    at /Users/chaofuyang/.nvm/versions/node/v20.10.0/lib/node_modules/promptfoo/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createShareableUrl (/Users/chaofuyang/.nvm/versions/node/v20.10.0/lib/node_modules/promptfoo/dist/src/share.js:24:27)
    at async runEvaluation (/Users/chaofuyang/.nvm/versions/node/v20.10.0/lib/node_modules/promptfoo/dist/src/main.js:451:67)
    at async Command.<anonymous> (/Users/chaofuyang/.nvm/versions/node/v20.10.0/lib/node_modules/promptfoo/dist/src/main.js:559:9) {
  type: 'invalid-json'
}
```

Looks like the API server returns 500 Internal server error

**Comment by typpo** [comment]
This has been fixed!  Sorry about that.
