### ISSUE TITLE
Browser exception (Minified React error #31; visit) when clicking magnifying glass in output

### ISSUE THREAD

**Issue by efung** [promptfoo/promptfoo#768]
Using promptfoo 0.57.1 on macOS 14.4. Chrome Version 124.0.6367.119 (Official Build) (arm64)

When viewing the Web UI, clicking on the magnifying glass (🔎) in the output works okay if the output dict is small.  But for some of our examples, we have a custom Python provider that returns a dictionary for `output` and some of the fields are very large. On those rows, clicking the magnifying glass results in this error in the browser console:

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bstatement%2C%20reason%2C%20verdict%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at nz (fd9d1056-a95b789c94c05ff6.js:9:29694)
    at d (fd9d1056-a95b789c94c05ff6.js:9:31594)
    at fd9d1056-a95b789c94c05ff6.js:9:33994
    at s (fd9d1056-a95b789c94c05ff6.js:9:34285)
    at u (fd9d1056-a95b789c94c05ff6.js:9:35368)
    at lo (fd9d1056-a95b789c94c05ff6.js:9:52233)
    at im (fd9d1056-a95b789c94c05ff6.js:9:115510)
    at oM (fd9d1056-a95b789c94c05ff6.js:9:90098)
    at fd9d1056-a95b789c94c05ff6.js:9:89920
    at oT (fd9d1056-a95b789c94c05ff6.js:9:89927)
window.console.error @ 596-f3a131b7c336dd5d.js:1
r9 @ fd9d1056-a95b789c94c05ff6.js:9
n.callback @ fd9d1056-a95b789c94c05ff6.js:9
nf @ fd9d1056-a95b789c94c05ff6.js:9
nd @ fd9d1056-a95b789c94c05ff6.js:9
am @ fd9d1056-a95b789c94c05ff6.js:9
ay @ fd9d1056-a95b789c94c05ff6.js:9
aT @ fd9d1056-a95b789c94c05ff6.js:9
ay @ fd9d1056-a95b789c94c05ff6.js:9
aT @ fd9d1056-a95b789c94c05ff6.js:9
ay @ fd9d1056-a95b789c94c05ff6.js:9
aT @ fd9d1056-a95b789c94c05ff6.js:9
ay @ fd9d1056-a95b789c94c05ff6.js:9
aT @ fd9d1056-a95b789c94c05ff6.js:9
ay @ fd9d1056-a95b789c94c05ff6.js:9
aT @ fd9d1056-a95b789c94c05ff6.js:9
ay @ fd9d1056-a95b789c94c05ff6.js:9
aT @ fd9d1056-a95b789c94c05ff6.js:9
ay @ fd9d1056-a95b789c94c05ff6.js:9
aT @ fd9d1056-a95b789c94c05ff6.js:9
ay @ fd9d1056-a95b789c94c05ff6.js:9
(anonymous) @ fd9d1056-a95b789c94c05ff6.js:9
oO @ fd9d1056-a95b789c94c05ff6.js:9
nG @ fd9d1056-a95b789c94c05ff6.js:9
nJ @ fd9d1056-a95b789c94c05ff6.js:9
(anonymous) @ fd9d1056-a95b789c94c05ff6.js:9
```

I realize this minified stack trace isn't that helpful but happy to try and provide more details. It's 100% reproducible.

**Comment by typpo** [comment]
Any chance you'd be able to share an eval with me that repros?  Using `promptfoo export <evalId> -o <outputpath>.json`
