### ISSUE TITLE
SQLITE_CONSTRAINT_NOT_NULL Error when running "promptfoo view"

### ISSUE THREAD

**Issue by tiffanycchen** [promptfoo/promptfoo#800]
"promptfoo eval" can be succesfully executed.
However, "promptfoo view" seems to have some operation with sqlite and is showing this error every time. Do you know how to fix it?
-----

🔁 Migrating 50 flat files to local database.
This is a one-time operation and may take a minute...
Backup of output directory created at /Users/tiffanychen/.promptfoo/output-backup-20240518
Moving files into database...

/usr/local/lib/node_modules/promptfoo/node_modules/drizzle-orm/better-sqlite3/session.cjs:79
    return this.stmt.run(...params);
                     ^
SqliteError: NOT NULL constraint failed: evals.created_at
    at PreparedQuery.run (/usr/local/lib/node_modules/promptfoo/node_modules/drizzle-orm/better-sqlite3/session.cjs:79:22)
    at QueryPromise.run (/usr/local/lib/node_modules/promptfoo/node_modules/drizzle-orm/sqlite-core/query-builders/insert.cjs:158:28)
    at writeResultsToDatabase (/usr/local/lib/node_modules/promptfoo/dist/src/util.js:424:10)
    at /usr/local/lib/node_modules/promptfoo/dist/src/util.js:583:19
    at Array.map (<anonymous>)
    at migrateResultsFromFileSystemToDatabase (/usr/local/lib/node_modules/promptfoo/dist/src/util.js:580:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startServer (/usr/local/lib/node_modules/promptfoo/dist/src/web/server.js:42:5)
    at async Command.<anonymous> (/usr/local/lib/node_modules/promptfoo/dist/src/main.js:253:9) {
  code: 'SQLITE_CONSTRAINT_NOTNULL'
}

Node.js v18.15.0

**Comment by typpo** [comment]
Thanks for the report.  Just got a fix in and published as 0.59.1

You can upgrade to 0.59.1, or reverting to a previous version (0.58.1) should work too.
