### ISSUE TITLE
Issue when using Vertex Gemini - "undefined" JSON Error

### ISSUE THREAD

**Issue by Liv140** [promptfoo/promptfoo#910]
Hi, 

running into issues with any vertex:gemini models, other models work fine. 

Have been using GOOGLE_APPLICATION_CREDENTIALS with the service account absolutely fine on Friday (07/06/2024) but same setup generates below errors today (Monday). 
The credentials file is a valid json.
Running this within a Jupyter notebook using promptfoo@latest (i.e.!npx promptfoo@latest eval -c promptfooconfig.yaml --no-progress-bar --share)

SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at VertexChatProvider.callGeminiApi (/Users/xxxx/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/vertex.js:120:40)
    at VertexChatProvider.callApi (/Users/xxxxx/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/providers/vertex.js:103:25)
    at Evaluator.runEval (/Users/xxxxx/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:273:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async processEvalStep (/Users/xxxx/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:601:25)

Any help with resolving this would be greatly appreciated!

**Comment by typpo** [comment]
Fixed in 0.63.1!
